### ISSUE TITLE
function Get-AADServicePrincipalEXOReport doesn't work as expected

### ISSUE THREAD

**Issue by zunkzunk** [IngoGege/Miscellaneous#1]
The inner function Test-ServicePrincipal should be changed to something like this:
```
function Test-ServicePrincipal
        {
            [OutputType([System.Boolean])]
            param(
                [Microsoft.Graph.PowerShell.Models.MicrosoftGraphServicePrincipal]
                $ServicePrincipal,

                [Microsoft.Graph.PowerShell.Models.MicrosoftGraphAppRole[]]
                $AppRoles
            )
            
            $bool = $false
            
            foreach ($AppRoleID in $ServicePrincipal.AppRoleAssignments.AppRoleId)
            {
                if ($AppRoles.Id.Contains($AppRoleID))
                {
                    $bool = $true
                }
            }
            if ($bool)
            {
                return $bool
            }
        }
```
Now it loops through all the app role assignments, but returns (exits) on the first item regardless of result.

**Comment by IngoGege** [comment]
Good point! Let me check!

**Comment by IngoGege** [comment]
Now, I remember why I did this:
Regardless of which roles, I want to have it reported. That's why I exited the function. If you use the switch IncludePolicyCheck, the function will then list all permissions. 
Does it make sense?

**Comment by zunkzunk** [comment]
Yes, but it doesn't work like that I think. 
In my case I have multiple SPNs that should be listed in the output, but aren't, because it just checks the first role assignment of the SPN. If the first one is not in the list, it returns with $false and the SPN is not listed in the output at all. It doesn't continue to loop through all of the role assignments. Never. It just bases the true/false of the first role assignment of that specific SPN.

**Comment by zunkzunk** [comment]
A return breaks the foreach loop. It always checks just the first role assignment. The break is also redundant and never used.
```
foreach ($AppRoleID in $ServicePrincipal.AppRoleAssignments.AppRoleId)
            {
                if ($AppRoles.Id.Contains($AppRoleID))
                {
                    return $true
                    break
                }
                else
                {
                    return $false
                }
            }
```

**Comment by IngoGege** [comment]
You're right! Thank you!
the issue is fixed:
https://github.com/IngoGege/Miscellaneous/commit/3fa769b0bcfea9a5419aa1790da8223cb45fb772

**Comment by zunkzunk** [comment]
Nice. Thank you! :)

**Comment by zunkzunk** [comment]
When I look at the code again the bool should probably be returned anyway, not just if true....

Anyway, it worked like this for me. Thank you again for providing these scripts :)

**Comment by IngoGege** [comment]
True...fixed!
